//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GUI.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NhanvienDto", Namespace="http://schemas.datacontract.org/2004/07/MyApp.DTO")]
    [System.SerializableAttribute()]
    public partial class NhanvienDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GioitinhField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HotenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ManhanvienField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> NgaysinhField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Gioitinh {
            get {
                return this.GioitinhField;
            }
            set {
                if ((object.ReferenceEquals(this.GioitinhField, value) != true)) {
                    this.GioitinhField = value;
                    this.RaisePropertyChanged("Gioitinh");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Hoten {
            get {
                return this.HotenField;
            }
            set {
                if ((object.ReferenceEquals(this.HotenField, value) != true)) {
                    this.HotenField = value;
                    this.RaisePropertyChanged("Hoten");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Manhanvien {
            get {
                return this.ManhanvienField;
            }
            set {
                if ((object.ReferenceEquals(this.ManhanvienField, value) != true)) {
                    this.ManhanvienField = value;
                    this.RaisePropertyChanged("Manhanvien");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Ngaysinh {
            get {
                return this.NgaysinhField;
            }
            set {
                if ((this.NgaysinhField.Equals(value) != true)) {
                    this.NgaysinhField = value;
                    this.RaisePropertyChanged("Ngaysinh");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DuanDto", Namespace="http://schemas.datacontract.org/2004/07/MyApp.DTO")]
    [System.SerializableAttribute()]
    public partial class DuanDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DiadiemField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MadaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TendaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Diadiem {
            get {
                return this.DiadiemField;
            }
            set {
                if ((object.ReferenceEquals(this.DiadiemField, value) != true)) {
                    this.DiadiemField = value;
                    this.RaisePropertyChanged("Diadiem");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mada {
            get {
                return this.MadaField;
            }
            set {
                if ((object.ReferenceEquals(this.MadaField, value) != true)) {
                    this.MadaField = value;
                    this.RaisePropertyChanged("Mada");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tenda {
            get {
                return this.TendaField;
            }
            set {
                if ((object.ReferenceEquals(this.TendaField, value) != true)) {
                    this.TendaField = value;
                    this.RaisePropertyChanged("Tenda");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NhanvienDuanDto", Namespace="http://schemas.datacontract.org/2004/07/MyApp.DTO")]
    [System.SerializableAttribute()]
    public partial class NhanvienDuanDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DiadiemField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HotenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MadaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ManvField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SogiocongField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TendaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Diadiem {
            get {
                return this.DiadiemField;
            }
            set {
                if ((object.ReferenceEquals(this.DiadiemField, value) != true)) {
                    this.DiadiemField = value;
                    this.RaisePropertyChanged("Diadiem");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Hoten {
            get {
                return this.HotenField;
            }
            set {
                if ((object.ReferenceEquals(this.HotenField, value) != true)) {
                    this.HotenField = value;
                    this.RaisePropertyChanged("Hoten");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mada {
            get {
                return this.MadaField;
            }
            set {
                if ((object.ReferenceEquals(this.MadaField, value) != true)) {
                    this.MadaField = value;
                    this.RaisePropertyChanged("Mada");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Manv {
            get {
                return this.ManvField;
            }
            set {
                if ((object.ReferenceEquals(this.ManvField, value) != true)) {
                    this.ManvField = value;
                    this.RaisePropertyChanged("Manv");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Sogiocong {
            get {
                return this.SogiocongField;
            }
            set {
                if ((this.SogiocongField.Equals(value) != true)) {
                    this.SogiocongField = value;
                    this.RaisePropertyChanged("Sogiocong");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tenda {
            get {
                return this.TendaField;
            }
            set {
                if ((object.ReferenceEquals(this.TendaField, value) != true)) {
                    this.TendaField = value;
                    this.RaisePropertyChanged("Tenda");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Nhanvien_GetAll", ReplyAction="http://tempuri.org/IService1/Nhanvien_GetAllResponse")]
        GUI.ServiceReference1.NhanvienDto[] Nhanvien_GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Nhanvien_GetAll", ReplyAction="http://tempuri.org/IService1/Nhanvien_GetAllResponse")]
        System.Threading.Tasks.Task<GUI.ServiceReference1.NhanvienDto[]> Nhanvien_GetAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Nhanvien_Insert", ReplyAction="http://tempuri.org/IService1/Nhanvien_InsertResponse")]
        void Nhanvien_Insert(GUI.ServiceReference1.NhanvienDto dto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Nhanvien_Insert", ReplyAction="http://tempuri.org/IService1/Nhanvien_InsertResponse")]
        System.Threading.Tasks.Task Nhanvien_InsertAsync(GUI.ServiceReference1.NhanvienDto dto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Nhanvien_Update", ReplyAction="http://tempuri.org/IService1/Nhanvien_UpdateResponse")]
        void Nhanvien_Update(GUI.ServiceReference1.NhanvienDto dto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Nhanvien_Update", ReplyAction="http://tempuri.org/IService1/Nhanvien_UpdateResponse")]
        System.Threading.Tasks.Task Nhanvien_UpdateAsync(GUI.ServiceReference1.NhanvienDto dto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Nhanvien_Delete", ReplyAction="http://tempuri.org/IService1/Nhanvien_DeleteResponse")]
        void Nhanvien_Delete(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Nhanvien_Delete", ReplyAction="http://tempuri.org/IService1/Nhanvien_DeleteResponse")]
        System.Threading.Tasks.Task Nhanvien_DeleteAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Duan_GetAll", ReplyAction="http://tempuri.org/IService1/Duan_GetAllResponse")]
        GUI.ServiceReference1.DuanDto[] Duan_GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Duan_GetAll", ReplyAction="http://tempuri.org/IService1/Duan_GetAllResponse")]
        System.Threading.Tasks.Task<GUI.ServiceReference1.DuanDto[]> Duan_GetAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Duan_Insert", ReplyAction="http://tempuri.org/IService1/Duan_InsertResponse")]
        void Duan_Insert(GUI.ServiceReference1.DuanDto dto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Duan_Insert", ReplyAction="http://tempuri.org/IService1/Duan_InsertResponse")]
        System.Threading.Tasks.Task Duan_InsertAsync(GUI.ServiceReference1.DuanDto dto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Duan_Update", ReplyAction="http://tempuri.org/IService1/Duan_UpdateResponse")]
        void Duan_Update(GUI.ServiceReference1.DuanDto dto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Duan_Update", ReplyAction="http://tempuri.org/IService1/Duan_UpdateResponse")]
        System.Threading.Tasks.Task Duan_UpdateAsync(GUI.ServiceReference1.DuanDto dto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Duan_Delete", ReplyAction="http://tempuri.org/IService1/Duan_DeleteResponse")]
        void Duan_Delete(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Duan_Delete", ReplyAction="http://tempuri.org/IService1/Duan_DeleteResponse")]
        System.Threading.Tasks.Task Duan_DeleteAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Nvd_Insert", ReplyAction="http://tempuri.org/IService1/Nvd_InsertResponse")]
        void Nvd_Insert(GUI.ServiceReference1.NhanvienDuanDto dto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Nvd_Insert", ReplyAction="http://tempuri.org/IService1/Nvd_InsertResponse")]
        System.Threading.Tasks.Task Nvd_InsertAsync(GUI.ServiceReference1.NhanvienDuanDto dto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Nvd_Update", ReplyAction="http://tempuri.org/IService1/Nvd_UpdateResponse")]
        void Nvd_Update(GUI.ServiceReference1.NhanvienDuanDto dto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Nvd_Update", ReplyAction="http://tempuri.org/IService1/Nvd_UpdateResponse")]
        System.Threading.Tasks.Task Nvd_UpdateAsync(GUI.ServiceReference1.NhanvienDuanDto dto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Nvd_Delete", ReplyAction="http://tempuri.org/IService1/Nvd_DeleteResponse")]
        void Nvd_Delete(string manv, string mada);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Nvd_Delete", ReplyAction="http://tempuri.org/IService1/Nvd_DeleteResponse")]
        System.Threading.Tasks.Task Nvd_DeleteAsync(string manv, string mada);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Nvd_GetReport", ReplyAction="http://tempuri.org/IService1/Nvd_GetReportResponse")]
        GUI.ServiceReference1.NhanvienDuanDto[] Nvd_GetReport();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Nvd_GetReport", ReplyAction="http://tempuri.org/IService1/Nvd_GetReportResponse")]
        System.Threading.Tasks.Task<GUI.ServiceReference1.NhanvienDuanDto[]> Nvd_GetReportAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : GUI.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<GUI.ServiceReference1.IService1>, GUI.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public GUI.ServiceReference1.NhanvienDto[] Nhanvien_GetAll() {
            return base.Channel.Nhanvien_GetAll();
        }
        
        public System.Threading.Tasks.Task<GUI.ServiceReference1.NhanvienDto[]> Nhanvien_GetAllAsync() {
            return base.Channel.Nhanvien_GetAllAsync();
        }
        
        public void Nhanvien_Insert(GUI.ServiceReference1.NhanvienDto dto) {
            base.Channel.Nhanvien_Insert(dto);
        }
        
        public System.Threading.Tasks.Task Nhanvien_InsertAsync(GUI.ServiceReference1.NhanvienDto dto) {
            return base.Channel.Nhanvien_InsertAsync(dto);
        }
        
        public void Nhanvien_Update(GUI.ServiceReference1.NhanvienDto dto) {
            base.Channel.Nhanvien_Update(dto);
        }
        
        public System.Threading.Tasks.Task Nhanvien_UpdateAsync(GUI.ServiceReference1.NhanvienDto dto) {
            return base.Channel.Nhanvien_UpdateAsync(dto);
        }
        
        public void Nhanvien_Delete(string id) {
            base.Channel.Nhanvien_Delete(id);
        }
        
        public System.Threading.Tasks.Task Nhanvien_DeleteAsync(string id) {
            return base.Channel.Nhanvien_DeleteAsync(id);
        }
        
        public GUI.ServiceReference1.DuanDto[] Duan_GetAll() {
            return base.Channel.Duan_GetAll();
        }
        
        public System.Threading.Tasks.Task<GUI.ServiceReference1.DuanDto[]> Duan_GetAllAsync() {
            return base.Channel.Duan_GetAllAsync();
        }
        
        public void Duan_Insert(GUI.ServiceReference1.DuanDto dto) {
            base.Channel.Duan_Insert(dto);
        }
        
        public System.Threading.Tasks.Task Duan_InsertAsync(GUI.ServiceReference1.DuanDto dto) {
            return base.Channel.Duan_InsertAsync(dto);
        }
        
        public void Duan_Update(GUI.ServiceReference1.DuanDto dto) {
            base.Channel.Duan_Update(dto);
        }
        
        public System.Threading.Tasks.Task Duan_UpdateAsync(GUI.ServiceReference1.DuanDto dto) {
            return base.Channel.Duan_UpdateAsync(dto);
        }
        
        public void Duan_Delete(string id) {
            base.Channel.Duan_Delete(id);
        }
        
        public System.Threading.Tasks.Task Duan_DeleteAsync(string id) {
            return base.Channel.Duan_DeleteAsync(id);
        }
        
        public void Nvd_Insert(GUI.ServiceReference1.NhanvienDuanDto dto) {
            base.Channel.Nvd_Insert(dto);
        }
        
        public System.Threading.Tasks.Task Nvd_InsertAsync(GUI.ServiceReference1.NhanvienDuanDto dto) {
            return base.Channel.Nvd_InsertAsync(dto);
        }
        
        public void Nvd_Update(GUI.ServiceReference1.NhanvienDuanDto dto) {
            base.Channel.Nvd_Update(dto);
        }
        
        public System.Threading.Tasks.Task Nvd_UpdateAsync(GUI.ServiceReference1.NhanvienDuanDto dto) {
            return base.Channel.Nvd_UpdateAsync(dto);
        }
        
        public void Nvd_Delete(string manv, string mada) {
            base.Channel.Nvd_Delete(manv, mada);
        }
        
        public System.Threading.Tasks.Task Nvd_DeleteAsync(string manv, string mada) {
            return base.Channel.Nvd_DeleteAsync(manv, mada);
        }
        
        public GUI.ServiceReference1.NhanvienDuanDto[] Nvd_GetReport() {
            return base.Channel.Nvd_GetReport();
        }
        
        public System.Threading.Tasks.Task<GUI.ServiceReference1.NhanvienDuanDto[]> Nvd_GetReportAsync() {
            return base.Channel.Nvd_GetReportAsync();
        }
    }
}
